# Generated by Django 5.2.5 on 2025-08-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket_tbl",
            fields=[
                ("Ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("Severity", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
