# Generated by Django 5.2.5 on 2025-08-22 05:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket_tbl",
            name="Classification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="Description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="Recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="Score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="TLP",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="Vulnerability",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acknowledged_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="assigned_responder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_responder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="file_enc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket_tbl",
            name="file_reference",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
