# Generated by Django 5.2.5 on 2025-08-22 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0002_ticket_tbl_classification_ticket_tbl_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IR_tbl",
            fields=[
                ("IR_id", models.AutoField(primary_key=True, serialize=False)),
                ("Actions_taken", models.TextField(blank=True, null=True)),
                ("Impact", models.TextField(blank=True, null=True)),
                ("Root_cause", models.TextField(blank=True, null=True)),
                ("Lessons_learned", models.TextField(blank=True, null=True)),
                ("Status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ticket",
                        to="dbcreate.ticket_tbl",
                    ),
                ),
            ],
        ),
    ]
