# Generated by Django 5.2.5 on 2025-08-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0003_ir_tbl"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("Role_id", models.AutoField(primary_key=True, serialize=False)),
                ("Role", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
