# Generated by Django 5.2.5 on 2025-08-22 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0004_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket_tbl",
            old_name="assigned_responder",
            new_name="Responder",
        ),
        migrations.CreateModel(
            name="Responder_tbl",
            fields=[
                ("Responder_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Resp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "Role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="dbcreate.roles",
                    ),
                ),
            ],
        ),
    ]
