# Generated by Django 5.2.5 on 2025-08-22 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0005_rename_assigned_responder_ticket_tbl_responder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_tbl",
            name="Responder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_responder",
                to="dbcreate.responder_tbl",
            ),
        ),
    ]
