# Generated by Django 5.2.5 on 2025-08-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0006_alter_ticket_tbl_responder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_tbl",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acknowledged_by",
                to="dbcreate.responder_tbl",
            ),
        ),
    ]
