# Generated by Django 5.2.5 on 2025-08-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0007_alter_ticket_tbl_acknowledged_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification_tbl",
            fields=[
                (
                    "Classification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "Classification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
