# Generated by Django 5.2.5 on 2025-08-22 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0008_classification_tbl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket_tbl",
            name="Classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_classification",
                to="dbcreate.classification_tbl",
            ),
        ),
    ]
