# Generated by Django 5.2.5 on 2025-08-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0009_alter_ticket_tbl_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Severity_tbl",
            fields=[
                ("Serverity_id", models.AutoField(primary_key=True, serialize=False)),
                ("Severity", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
