# Generated by Django 5.2.5 on 2025-08-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0011_alter_ticket_tbl_severity"),
    ]

    operations = [
        migrations.CreateModel(
            name="TLP_tbl",
            fields=[
                ("TLP_id", models.AutoField(primary_key=True, serialize=False)),
                ("TLP", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
