# Generated by Django 5.2.5 on 2025-09-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0013_alter_ticket_tbl_tlp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status_tbl",
            fields=[
                ("Status_id", models.AutoField(primary_key=True, serialize=False)),
                ("Status", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
