# Generated by Django 5.2.5 on 2025-09-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0015_alter_ir_tbl_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket_tbl",
            name="Ticket_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
