# Generated by Django 5.2.5 on 2025-09-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0016_ticket_tbl_ticket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tlp_tbl",
            name="Description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
