# Generated by Django 5.2.5 on 2025-09-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0018_severity_tbl_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification_tbl",
            name="Description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
