# Generated by Django 5.2.5 on 2025-09-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0019_classification_tbl_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responder_tbl",
            name="Role",
        ),
        migrations.AddField(
            model_name="responder_tbl",
            name="Roles",
            field=models.ManyToManyField(
                blank=True, related_name="responders", to="dbcreate.roles"
            ),
        ),
    ]
