# Generated by Django 5.2.5 on 2025-09-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0020_remove_responder_tbl_role_responder_tbl_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genders",
            fields=[
                ("Gender_id", models.AutoField(primary_key=True, serialize=False)),
                ("Gender", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
