# Generated by Django 5.2.5 on 2025-09-10 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbcreate", "0021_genders"),
    ]

    operations = [
        migrations.AddField(
            model_name="responder_tbl",
            name="Gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gender",
                to="dbcreate.genders",
            ),
        ),
    ]
